/**
 * Durable Job State Machine for FlowCraft AI Studio
 * Enforces explicit states, deterministic transitions, and recovery metadata.
 */

export const JOB_STATES = Object.freeze({
  // Normal operational progression
  QUEUED: 'QUEUED',
  PREPARING: 'PREPARING',
  READY: 'READY',
  SUBMITTING: 'SUBMITTING',
  SUBMITTED: 'SUBMITTED',
  GENERATING: 'GENERATING',
  GENERATED: 'GENERATED',
  DOWNLOADING: 'DOWNLOADING',
  VERIFYING: 'VERIFYING',
  COMPLETED: 'COMPLETED',

  // Paused / Recovery states
  PAUSED: 'PAUSED',
  RETRY_WAIT: 'RETRY_WAIT',
  NETWORK_ERROR: 'NETWORK_ERROR',
  RATE_LIMITED: 'RATE_LIMITED',
  PROTECTION_DETECTED: 'PROTECTION_DETECTED',
  AUTH_REQUIRED: 'AUTH_REQUIRED',
  UI_CHANGED: 'UI_CHANGED',
  GENERATION_TIMEOUT: 'GENERATION_TIMEOUT',
  DOWNLOAD_FAILED: 'DOWNLOAD_FAILED',
  UNKNOWN_ERROR: 'UNKNOWN_ERROR',
  NEEDS_RECOVERY: 'NEEDS_RECOVERY'
});

export const VALID_TRANSITIONS = Object.freeze({
  [JOB_STATES.QUEUED]: [
    JOB_STATES.PREPARING,
    JOB_STATES.PAUSED,
    JOB_STATES.NETWORK_ERROR,
    JOB_STATES.AUTH_REQUIRED
  ],
  [JOB_STATES.PREPARING]: [
    JOB_STATES.READY,
    JOB_STATES.PAUSED,
    JOB_STATES.UI_CHANGED,
    JOB_STATES.AUTH_REQUIRED,
    JOB_STATES.NETWORK_ERROR,
    JOB_STATES.RETRY_WAIT
  ],
  [JOB_STATES.READY]: [
    JOB_STATES.SUBMITTING,
    JOB_STATES.PAUSED,
    JOB_STATES.PROTECTION_DETECTED,
    JOB_STATES.RATE_LIMITED,
    JOB_STATES.UI_CHANGED,
    JOB_STATES.NETWORK_ERROR
  ],
  [JOB_STATES.SUBMITTING]: [
    JOB_STATES.SUBMITTED,
    JOB_STATES.PAUSED,
    JOB_STATES.PROTECTION_DETECTED,
    JOB_STATES.RATE_LIMITED,
    JOB_STATES.NETWORK_ERROR,
    JOB_STATES.UI_CHANGED,
    JOB_STATES.RETRY_WAIT
  ],
  [JOB_STATES.SUBMITTED]: [
    JOB_STATES.GENERATING,
    JOB_STATES.GENERATED,
    JOB_STATES.PAUSED,
    JOB_STATES.GENERATION_TIMEOUT,
    JOB_STATES.PROTECTION_DETECTED,
    JOB_STATES.RATE_LIMITED,
    JOB_STATES.NETWORK_ERROR
  ],
  [JOB_STATES.GENERATING]: [
    JOB_STATES.GENERATED,
    JOB_STATES.PAUSED,
    JOB_STATES.GENERATION_TIMEOUT,
    JOB_STATES.PROTECTION_DETECTED,
    JOB_STATES.RATE_LIMITED,
    JOB_STATES.NETWORK_ERROR,
    JOB_STATES.RETRY_WAIT
  ],
  [JOB_STATES.GENERATED]: [
    JOB_STATES.DOWNLOADING,
    JOB_STATES.PAUSED,
    JOB_STATES.DOWNLOAD_FAILED,
    JOB_STATES.NETWORK_ERROR
  ],
  [JOB_STATES.DOWNLOADING]: [
    JOB_STATES.VERIFYING,
    JOB_STATES.DOWNLOAD_FAILED,
    JOB_STATES.NETWORK_ERROR,
    JOB_STATES.PAUSED,
    JOB_STATES.RETRY_WAIT
  ],
  [JOB_STATES.VERIFYING]: [
    JOB_STATES.COMPLETED,
    JOB_STATES.DOWNLOAD_FAILED,
    JOB_STATES.PAUSED,
    JOB_STATES.RETRY_WAIT
  ],
  [JOB_STATES.COMPLETED]: [], // Terminal state

  // Failure and recovery state transitions
  [JOB_STATES.PAUSED]: [
    JOB_STATES.PREPARING,
    JOB_STATES.READY,
    JOB_STATES.SUBMITTING,
    JOB_STATES.SUBMITTED,
    JOB_STATES.GENERATING,
    JOB_STATES.GENERATED,
    JOB_STATES.DOWNLOADING,
    JOB_STATES.VERIFYING,
    JOB_STATES.RETRY_WAIT,
    JOB_STATES.NEEDS_RECOVERY
  ],
  [JOB_STATES.RETRY_WAIT]: [
    JOB_STATES.PREPARING,
    JOB_STATES.READY,
    JOB_STATES.SUBMITTING,
    JOB_STATES.GENERATING,
    JOB_STATES.DOWNLOADING,
    JOB_STATES.PAUSED,
    JOB_STATES.NEEDS_RECOVERY
  ],
  [JOB_STATES.NETWORK_ERROR]: [
    JOB_STATES.RETRY_WAIT,
    JOB_STATES.PAUSED,
    JOB_STATES.NEEDS_RECOVERY
  ],
  [JOB_STATES.RATE_LIMITED]: [
    JOB_STATES.PAUSED,
    JOB_STATES.RETRY_WAIT,
    JOB_STATES.NEEDS_RECOVERY
  ],
  [JOB_STATES.PROTECTION_DETECTED]: [
    JOB_STATES.PAUSED,
    JOB_STATES.NEEDS_RECOVERY
  ],
  [JOB_STATES.AUTH_REQUIRED]: [
    JOB_STATES.PAUSED,
    JOB_STATES.PREPARING
  ],
  [JOB_STATES.UI_CHANGED]: [
    JOB_STATES.PAUSED,
    JOB_STATES.RETRY_WAIT,
    JOB_STATES.NEEDS_RECOVERY
  ],
  [JOB_STATES.GENERATION_TIMEOUT]: [
    JOB_STATES.PAUSED,
    JOB_STATES.RETRY_WAIT,
    JOB_STATES.GENERATED, // In case tile completed while timing out
    JOB_STATES.NEEDS_RECOVERY
  ],
  [JOB_STATES.DOWNLOAD_FAILED]: [
    JOB_STATES.DOWNLOADING, // Direct retry of download without re-generation!
    JOB_STATES.PAUSED,
    JOB_STATES.RETRY_WAIT,
    JOB_STATES.NEEDS_RECOVERY
  ],
  [JOB_STATES.UNKNOWN_ERROR]: [
    JOB_STATES.PAUSED,
    JOB_STATES.RETRY_WAIT,
    JOB_STATES.NEEDS_RECOVERY
  ],
  [JOB_STATES.NEEDS_RECOVERY]: [
    JOB_STATES.PAUSED,
    JOB_STATES.PREPARING,
    JOB_STATES.READY,
    JOB_STATES.GENERATING,
    JOB_STATES.DOWNLOADING
  ]
});

export class DurableStateMachine {
  static canTransition(fromState, toState) {
    if (fromState === toState) return true;
    const allowed = VALID_TRANSITIONS[fromState];
    return Array.isArray(allowed) && allowed.includes(toState);
  }

  static isTerminal(state) {
    return state === JOB_STATES.COMPLETED;
  }

  static isFailure(state) {
    return [
      JOB_STATES.NETWORK_ERROR,
      JOB_STATES.RATE_LIMITED,
      JOB_STATES.PROTECTION_DETECTED,
      JOB_STATES.AUTH_REQUIRED,
      JOB_STATES.UI_CHANGED,
      JOB_STATES.GENERATION_TIMEOUT,
      JOB_STATES.DOWNLOAD_FAILED,
      JOB_STATES.UNKNOWN_ERROR
    ].includes(state);
  }

  static isPausable(state) {
    return state !== JOB_STATES.COMPLETED;
  }

  static isResumable(state) {
    return [
      JOB_STATES.PAUSED,
      JOB_STATES.RETRY_WAIT,
      JOB_STATES.NEEDS_RECOVERY,
      JOB_STATES.NETWORK_ERROR,
      JOB_STATES.RATE_LIMITED,
      JOB_STATES.PROTECTION_DETECTED,
      JOB_STATES.DOWNLOAD_FAILED
    ].includes(state);
  }
}
